version: '1'

services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
volumes:
  redis: